version: "3.8"

services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - "8004:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
      - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - 9004:80
#Run this command after docker installation.
#docker-php-ext-install pdo_mysql
#docker-php-ext-enable pdo_mysql
